sudo: required
language: bash
sudo: required
dist: xenial
addons:
  sonarcloud:
    organization: "drew-holt-github" # the key of the org you chose at step #3
    token:
      secure: u5RX3uF51zXUjp8ZIayDXsxVSPuS71hpBmRqt443p0QDtcloVlaAB5FhahCXuHjKn9dDLbydq8qO0+vPabAwmvssrd6hIgRD0TDRlfgfmr+QeoKNQL6+CL9WI1q+IbDIL5ZAvdntmnQhPICULGvMK4pZozylU7jZrCM4H1Q2R2HAbiFJ24OR5ZNeQ6HZI3lG6wAKTO/qTf/aZq9VXIi4jdrMlpb/iPUOsLJAh1hm6MFi8bFkNbXVdvWG1sEp8cca4PJJ/XS6ExTEuGeIXoJa0aRGdw/JLCWDGLerOTZU7GSrCz9RrtogTXVtrz8bOXQkQp8/ddmL3c2LrC1Yu37VBiHX+JRaTnQEmT7PRpyBlFq73NJXcA7ywNSX82subwvOg7+2YgDDC/tbEFOFwVv6ZE0pC82ZN9K+ApzilDuginfTy6RM+JNBAo5arGoJYD+bymWa1MhknhrBGBNv5j0a6MLg9yXexVvwBAE1ysKBI6djgvei1lYI3L6sPCc2L3tHpck6x2/4PLwZYjAVElS24bvmPu9sIwzEG3DSWRD2EqAFpQxLmrIbDgfhq5zMzvpXiCM5cexezPQ1hC8Ht5zlwaPg5XJKJrbYPzghkOm77z76ENZt3BjyotH/utKW7mczmn1rOrzxdiawgXtUWP/MX/iy/OJkCIJb0Yj71HjCjU8=
env:
- SONAR_SCANNER_HOME=$HOME/.sonarscanner/sonar-scanner-2.8
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y shellcheck kcov
script:
- shellcheck -x *.sh
- sonar-scanner
after_success: |
  for i in `ls *.sh`; do kcov coverage-$i $i; done;
  bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: eJDlV4SfjtqEyULY7xvXH/bXOE3gEWKggldiPYkN8AP2f6Ct2Xs6PaCPUXea1XFsSzdJLtwnge2FXqqWId/LT/7T8zOlyoLMpbUs4YItjWRoFur1WyjFozVCV6uB/QxGqNJJIltnlkfDmqChoogz9vHPftr1lg72EfVwzKsbGkJBDgMDpIQ6CV1+ITieekXpGagkTPQVlwzjHHfcHMcUVdQdsaiLW2kT7FOQk55gd7Ze/wCJj1DT2QF4ktZVY8btb+DTGOLSaiuk2O74xh+VVJK8bWJG/hgklsBr9g4hIsYLt4/EtBXODTaemRoFVRPP6PeiPjAFzPHnv/TyV7BXU75eOoZKlFfOl9/OvOgeZIqBpG0ccZ8YApfUyQyJJSO4bAC17qIdeewdVrhnlvKab554E4OIwA7XmsqTRqP3WhSMQ2RFXVoMfJm6s+uSXpavkp/VjmAZgMZDTUSaK2oqJhRmEwSyycmh/KGyf3eQhxjuDOycA6jb5OMMGbbkLMPOLDoHW7BY57Voo4m+qRDfSoD4I9/A0pD56xWtFqtqQmvprHEIHr+b9JuFwOhPAZ4zISPfMh0XsJ0lSMmkYnIgurMkGlGfLvcDeX/LuCAJtAtR4w48JjFw/wPFgAMYgFNaaY2sx20mTeG7Xyy0mL8hzNayCRE4MFPLAQCo9Z4dmUA=
